import test from 'node:test';
import assert from 'node:assert/strict';
import {loadCatnu} from './helpers/load-app.mjs';
function fixture(C){return C.prepareRedesign({schemaVersion:2,cats:[{id:'a',name:'A'},{id:'b',name:'B'},{id:'c',name:'C'}],logs:[{catId:'a',note:'keep me'}],quests:{old:[]},settings:{},streak:{current:2},milestones:[]});}
test('redesign migration preserves original cats, logs, quests and unknown fields',()=>{const C=loadCatnu(); const s=fixture(C);s.customField={keep:true};const m=C.migrateState(JSON.parse(JSON.stringify(s)));assert.equal(m.logs[0].note,'keep me');assert.equal(m.cats.length,3);assert.equal(m.customField.keep,true);assert.equal(m.schemaVersion,2);assert.equal(m.settings.locale,'zh-HK');assert.equal(m.assets.length,0);});
test('one daily cat rotates across a three-cat household deterministically',()=>{const C=loadCatnu();const s=fixture(C);const ids=['2026-09-13','2026-09-14','2026-09-15'].map(d=>C.dailyCat(s,d).id);assert.equal(new Set(ids).size,3);assert.equal(C.dailyCat(s,'2026-09-13').id,ids[0]);});
test('owner impressions remain separate; feedback reduces confidence and revises insight',()=>{const C=loadCatnu();const s=fixture(C);s.cats[0].ownerPerception=['independent'];for(let i=0;i<6;i++)s.observations.push({catId:'a',answer:'yes'});assert.equal(C.insight(s,'a').trait,'social');assert.equal(C.insight(s,'a').confidence,'growing');s.insightFeedback.push({catId:'a',answer:'inaccurate'});assert.equal(C.insight(s,'a').revised,true);assert.equal(C.insight(s,'a').confidence,'low');assert.equal(s.cats[0].ownerPerception[0],'independent');});
test('four locales have identical complete translation keys; region does not overwrite locale',()=>{const C=loadCatnu();const s=fixture(C);s.settings.locale='en';s.settings.region='TW';C.prepareRedesign(s);assert.equal(s.settings.locale,'en');const keys=Object.keys(C.COPY.en).sort();for(const l of C.LOCALES){assert.deepEqual(Object.keys(C.COPY[l]).sort(),keys);assert.ok(Object.values(C.COPY[l]).every(v=>typeof v==='string'&&v.length));}});
test('shared memory stores a single asset and survives backup migration',()=>{const C=loadCatnu();const s=fixture(C);s.assets.push({id:'p',data:'data:image/jpeg;base64,abc'});s.moments.push({id:'m',assetId:'p',catIds:['a','b','c'],note:'family'});const m=C.migrateState(JSON.parse(JSON.stringify(s)));assert.equal(m.assets.length,1);assert.equal(m.moments[0].catIds.length,3);assert.equal(m.moments[0].assetId,m.assets[0].id);assert.equal(C.entitlements.multiCat,true);assert.equal(C.entitlements.billing,false);assert.equal(C.commerce.live,false);});
test('commerce adapter is region-aware, physical only, and never sponsors an unrelated or disputed pick',()=>{const C=loadCatnu();const s=fixture(C);s.settings.region='TW';s.observations.push({catId:'a',answer:'yes',question:'quiet-approach'});let p=C.getDemoPicks(s,'a');assert.equal(p[0].region,'TW');assert.equal(p[0].sponsored,true);assert.equal(p[0].reason,'match');assert.equal(p[1].reason,'neutral');assert.ok(p.every(p=>p.physical&&p.mock&&p.provider==='demo'));s.insightFeedback.push({catId:'a',answer:'inaccurate'});p=C.getDemoPicks(s,'a');assert.ok(p.every(p=>!p.sponsored&&p.reason==='neutral'));assert.ok(C.getDemoPicks(s,'all').every(p=>p.reason==='shared'));});
test('restore validation rejects missing assets, duplicate cat IDs, and malformed relationship records',()=>{const C=loadCatnu();const s=fixture(C);assert.equal(C.validateBackup(s),true);s.moments.push({catIds:['a','b'],assetId:'missing'});assert.equal(C.validateBackup(s),false);s.assets.push({id:'missing',data:'data:image/jpeg;base64,abc'});assert.equal(C.validateBackup(s),true);s.relationships.push({catIds:['a','a'],kind:'together'});assert.equal(C.validateBackup(s),false);s.relationships=[];s.cats[1].id='a';assert.equal(C.validateBackup(s),false);});
test('three situational questions rotate without increasing household workload',()=>{const C=loadCatnu();const s=fixture(C);const rows=Array.from({length:9},(_,i)=>C.dailyQuestion(s,`2026-09-${String(13+i).padStart(2,'0')}`));assert.equal(new Set(rows).size,3);assert.ok(rows.every(q=>['quiet-approach','toy-interest','settle-rest'].includes(q)));});
